language: elixir
sudo: false
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
script: mix test --trace --color
after_success:
    "curl $DEPLOYHOOK"
